name             'reddit'
maintainer       'Andrew DuFour'
maintainer_email 'andy.k.dufour@gmail.com'
license          'All rights reserved'
description      'Installs/Configures reddit'
long_description 'Installs/Configures reddit'
version          '0.1.0'

depends 'java'
depends 'database'
depends 'postgresql'
depends 'cassandra'
depends 'rabbitmq'
depends 'memcached'